### ISSUE TITLE
make post view when clicked marker

### ISSUE THREAD

**Issue by yomizo** [yomizo/respect-app#21]
### Road map

- [x]  router view apply modal and manage child component 

- [x]  refactering methods and variable

- [x]  when view change, check it is token true

- [x]  Search google marker having lat lng data

- [x]  think about sending token signined user to HTTP request 

- [x]  make popup view

- [x]  handle click event

- [x]  make function get post data
