### ISSUE TITLE
Create roadmap for function "Metoo"

### ISSUE THREAD

**Issue by yomizo** [yomizo/respect-app#37]
### View
- [ ] create "Metoo" btn on "Postshow" SFC.
- [ ] change view btn active/unactive depending on signin user.
- [ ] When current user postshow btn(marker), request with params(post_id & user_id)
- [ ] If it's data is found, btn is active. if not, unactive.

### Click Event
- [ ] When user btn click, this event is handled me.
- [ ] After event handle. In `store.js` request post metoo table in DB.
